# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
#if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
#fi

source ~/.zplug/init.zsh
source ~/.zsh/plug.zsh

source ~/.zsh/aliases.zsh
source ~/.zsh/bps.zsh
source ~/.zsh/path.zsh
source ~/.zsh/fzf.zsh

source ~/.zsh/pyenv.zsh
source ~/.zsh/cargo.zsh

source ~/.zsh/settings.zsh

# Then, source plugins and add commands to $PATH
zplug load

# Created by FZF installer
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
